AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Config Rule's lambda function.

Resources:
  IAMUsersComplianceFunction:
    Properties:
      CodeUri: ../src/
      FunctionName: IAMUsersComplianceFunction
      Handler: lambda.lambda_handler
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: python2.7
      Timeout: 30
    Type: AWS::Serverless::Function
  LambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:*
            - config:PutEvaluations
            - config:GetResourceConfigHistory
            - config:ListDiscoveredResources
            - iam:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: root
    Type: AWS::IAM::Role
Outputs:
  IAMUsersComplianceFunctionFnName:
    Description: Name of the IAMUsersComplianceFunction lambda function
    Export:
      Name: IAMUsersComplianceFunction
    Value:
      Ref: IAMUsersComplianceFunction
